### PR TITLE
chinese simplified translation

### PR DESCRIPTION
**Pull request by WanderMax**
done translation file, may need add language entry in source code

### CODE REVIEW

**Comment by mrdude2478** [comment]
See here,

https://github.com/mrdude2478/TinWoo/tree/Main/romfs/lang

In the tw.json file, I already updated the chinese stuff. Look in that file to see if anything needs modded.

**Comment by WanderMax** [comment]
add chinese simplified entry into lang.cpp and little translation fix.
anyway, I put chinese simplified translation file 'custom.json' into /switch/tinwoo/lang/custom.json, but app crash at startup.

**Comment by mrdude2478** [comment]
> add chinese simplified entry into lang.cpp and little translation fix. anyway, I put chinese simplified translation file 'custom.json' into /switch/tinwoo/lang/custom.json to test, but app crash at startup.

Yes that's happened because I have been adding updates to the souce code, you need to download the source and compile it so that the custom language works - don't use the version in the release page.

**Comment by mrdude2478** [comment]
Closed for now as all the mods you posted for langauge change are already done in TW language, which is the same as Chinese.

**Comment by WanderMax** [comment]
TW is totally different from Chinese simplified, they have different language codes. TW is Chinese traditional, code zh-TW, usually used in China Taiwan. CN is Chinese simplified, code zh-CN, usually used in China mainland. You can search wiki for details.

**Comment by mrdude2478** [comment]
> I feel sad for your hasty action. TW is totally different from Chinese simplified, they have different language codes. TW is Chinese traditional, code zh-TW, usually used in China Taiwan. CN is Chinese simplified, code zh-CN, usually used in China mainland. You can search wiki for details.

Well download the tw language file from the git (yes the latest file, not an old one) and mod it line by line, I will compare it and check it on google translate and if it's done properly I will mod the settings page and add the country flag etc. There's more to adding a language than just adding the langauge file.

**Comment by mrdude2478** [comment]
Chinese added, you should have tested the language file before testing I spent about a hour fixing the broken stuff in it, also I removed the communist propoganda, nobody wants to see that shit when they just want to install a game.

**Comment by WanderMax** [comment]
great work bro. thanks!

**Pull request closed without merging**
